### ISSUE TITLE
安装插件后，无法生效

### ISSUE THREAD

**Issue by fatwang2** [LlmKira/llmbot_plugin_bilisearch#1]
看了git，也看了网站，真心没看懂到底咋用插件的

**Comment by sudoskys** [comment]
现在才发现你的留言，哎呀。
程序启动的时候会自动加载。
在项目环境里面安装就可以了。
无法生效大概是没有装到一个环境里面。

**Comment by sudoskys** [comment]
整体架构已经完成第四次重构，故关闭此议题
